### PR TITLE
Fix build errors for Rust 1.82 toolchain

### PR DESCRIPTION
**Pull request by manologab**
This should fix the build errors in the latest rust toolchain

### CODE REVIEW

**Comment by Noeda** [comment]
Lemme check this builds fine on my side, and then I can merge. (Which I apparently can do...forgot this repository exists). One moment please.

**Comment by Noeda** [comment]
Having a bit of compilation issues, but I think it's because the codebase has rotted quite a bit. Maybe the `traildb-sys` dir needs some updating. One more moments please.

**Comment by Noeda** [comment]
Alright, it compiles. (I forgot to change to your branch meaning I was actually just building the regular `master` and failing...because this PR fixes that 🤦 ). Just checking due diligence that some older stable rusts still work and then can clickety clack merge.

**Comment by Noeda** [comment]
All looks good. Earliest version of Rust that doesn't work is 1.77.0 it seems (tested one by one), but otherwise, nightly and all recent Rusts work.

**Comment by manologab** [comment]
Thank You!

**Pull request merged**
